# Site settings
title: mkropat on Github
email: mail@michael.kropat.name
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mkropat.github.io" # the base hostname & protocol for your site
twitter_username: MichaelKropat
github_username:  mkroapt

# Build settings
markdown: redcarpet
