plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima

# Site settings
title: codetinkerer.com
author: Michael Kropat
email: mail@michael.kropat.name
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.codetinkerer.com" # the base hostname & protocol for your site
twitter_username: MichaelKropat
github_username:  mkropat
description: Home page of Michael Kropat
show_excerpts: true
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
