# Site settings
title: codetinkerer.com
email: mail@michael.kropat.name
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.codetinkerer.com" # the base hostname & protocol for your site
twitter_username: MichaelKropat
github_username:  mkropat

# Build settings
markdown: redcarpet
